spring.application.name=ecuritydemo
spring.security.user.name=shivansh
spring.security.user.password=demo@123

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=password

spring.app.jwtSecret=mewoncin127n!
spring.app.jwtExpirationMs=3000000
